name: universal_dice
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  path: any
  #  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  #image: ^3.3.0
  #flutter_image_compress: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Consolas
      fonts:
        - asset: resources/fonts/consolas/consolas.ttf
    - family: Oswald
      fonts:
        - asset: resources/fonts/oswald/oswald.ttf
